//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class air_quality
    {
        public int air_id { get; set; }
        public string air_station_name { get; set; }
        public Nullable<float> air_lat { get; set; }
        public Nullable<float> air_long { get; set; }
        public Nullable<float> air_no2 { get; set; }
        public Nullable<float> air_o3 { get; set; }
        public Nullable<float> air_co { get; set; }
        public Nullable<float> air_pm10 { get; set; }
        public Nullable<float> air_pm2_5 { get; set; }
        public Nullable<System.DateTime> air_date { get; set; }
        public Nullable<System.TimeSpan> air_time { get; set; }
    }
}
