//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject_template_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Climate
    {
        public int Id { get; set; }
        public string state { get; set; }
        public Nullable<double> state_lat { get; set; }
        public Nullable<double> state_long { get; set; }
        public Nullable<double> temp_change { get; set; }
        public Nullable<double> avr_rainfall { get; set; }
    }
}
