//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class current_climate
    {
        public int current_id { get; set; }
        public Nullable<float> current_lat { get; set; }
        public Nullable<float> current_long { get; set; }
        public Nullable<System.DateTime> current_date_val { get; set; }
        public Nullable<System.TimeSpan> current_time_val { get; set; }
        public Nullable<float> current_temp { get; set; }
        public Nullable<int> current_humidity { get; set; }
        public Nullable<int> current_pressure { get; set; }
        public Nullable<float> current_wind_speed { get; set; }
        public Nullable<sbyte> current_is_cloud { get; set; }
        public Nullable<sbyte> current_is_clear { get; set; }
        public Nullable<sbyte> current_is_rain { get; set; }
    }
}
