//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject_template_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapModelTable
    {
        public int Id { get; set; }
        public Nullable<int> task1 { get; set; }
        public Nullable<int> task2 { get; set; }
        public Nullable<int> task3 { get; set; }
        public Nullable<int> task4 { get; set; }
        public Nullable<int> task5 { get; set; }
        public Nullable<int> task6 { get; set; }
        public Nullable<int> net_emissions { get; set; }
        public Nullable<int> rainfall_percentage { get; set; }
        public Nullable<int> Temperature { get; set; }
        public Nullable<int> total_water_consumption { get; set; }
        public Nullable<int> total_water_use { get; set; }
    }
}
