//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject_template_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTable
    {
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public string VIDEOTASK { get; set; }
        public string CTASK1 { get; set; }
        public string CTASK2 { get; set; }
        public string CTASK3 { get; set; }
        public string CTASK4 { get; set; }
        public string CTASK5 { get; set; }
        public string CTASK6 { get; set; }
    }
}
