CREATE TABLE [dbo].[userTable]
(
    [ID] INT NOT NULL PRIMARY KEY,
	[USERNAME] VARCHAR(MAX) NULL, 
    [PASSWORD] VARCHAR(MAX) NULL, 
    [EMAIL] VARCHAR(MAX) NULL, 
    [VIDEOTASK] VARCHAR(MAX) NULL, 
    [CTASK1] VARCHAR(MAX) NULL, 
    [CTASK2] VARCHAR(MAX) NULL, 
    [CTASK3] VARCHAR(MAX) NULL, 
    [CTASK4] VARCHAR(MAX) NULL, 
    [CTASK5] VARCHAR(MAX) NULL, 
    [CTASK6] VARCHAR(MAX) NULL
)
