//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancer_by_state_stats
    {
        public cancer_by_state_stats()
        {
            this.cancer_inc_mort_stats = new HashSet<cancer_inc_mort_stats>();
        }
    
        public int state_stats_id { get; set; }
        public string icd_codes { get; set; }
        public string cancer_group { get; set; }
        public Nullable<int> year { get; set; }
        public string state { get; set; }
        public string sex { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual location location { get; set; }
        public virtual ICollection<cancer_inc_mort_stats> cancer_inc_mort_stats { get; set; }
    }
}
