//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancer_inc_mort_stats
    {
        public cancer_inc_mort_stats()
        {
            this.cancer_by_state_stats = new HashSet<cancer_by_state_stats>();
        }
    
        public int inc_mort_stats_id { get; set; }
        public string icd_codes { get; set; }
        public string cancer_group { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> lower_age { get; set; }
        public Nullable<int> upper_age { get; set; }
        public string sex { get; set; }
        public Nullable<int> count { get; set; }
        public string datatype { get; set; }
    
        public virtual ICollection<cancer_by_state_stats> cancer_by_state_stats { get; set; }
    }
}
