//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onboarding.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sunpro_databaseEntities2 : DbContext
    {
        public sunpro_databaseEntities2()
            : base("name=sunpro_databaseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cancer_by_state_stats> cancer_by_state_stats { get; set; }
        public DbSet<cancer_inc_mort_stats> cancer_inc_mort_stats { get; set; }
        public DbSet<location> locations { get; set; }
        public DbSet<melbourne_uvi> melbourne_uvi { get; set; }
    }
}
