//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentNewMap
    {
        public int Id { get; set; }
        public string state { get; set; }
        public Nullable<double> state_lat { get; set; }
        public Nullable<double> state_long { get; set; }
        public Nullable<int> Temperature { get; set; }
        public Nullable<int> net_emissions { get; set; }
        public Nullable<int> rainfall_percentage { get; set; }
        public Nullable<int> total_water_use { get; set; }
        public Nullable<int> total_water_consumption { get; set; }
    }
}
