//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historical_climate
    {
        public int hist_id { get; set; }
        public string hist_name { get; set; }
        public Nullable<float> hist_lat { get; set; }
        public Nullable<float> hist_long { get; set; }
        public Nullable<int> hist_year { get; set; }
        public Nullable<float> hist_percentage { get; set; }
    }
}
