//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class main1_databaseEntities : DbContext
    {
        public main1_databaseEntities()
            : base("name=main1_databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<air_quality> air_quality { get; set; }
        public DbSet<current_climate> current_climate { get; set; }
        public DbSet<historical_climate> historical_climate { get; set; }
    }
}
