//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTable
    {
        public int Id { get; set; }
        public string Questions { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public int A1Carbon { get; set; }
        public int A1Water { get; set; }
        public int A1EcoLife { get; set; }
        public int A2Carbon { get; set; }
        public int A2Water { get; set; }
        public int A2EcoLife { get; set; }
    }
}
